-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deletedAt" TIMESTAMP(3) DEFAULT null,
ADD COLUMN     "role" TEXT NOT NULL DEFAULT 'colaborator',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT null;
